FROM python:3.6-alpine 
RUN mkdir /install
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install psycopg2-binary

WORKDIR /app/

ENTRYPOINT [ "python", "data_exporter.py" ]

CMD []